/*
 *
 * CfgParserException.h header template generated by fclass
 * Creation date : Sun May 20 21:27:54 2012
 *
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 *
 * Written by : rete
 */


#ifndef CFGPARSEREXCEPTION_HH
#define CFGPARSEREXCEPTION_HH

#include <iostream>
#include <string>
#include <cstdlib>
#include <exception>


namespace cfgparser {



	/*!
	 *
	 * @brief CfgParserExeption class.
	 * Responsible to throw exception for while using the CfgParser class
	 *
	 */
	class CfgParserException : public std::exception {

	protected :
		std::string error;

	public :
		/*!
		 *
		 * @brief Thrown constructor
		 *
		 */
		CfgParserException(std::string const& er) throw() : error(er)  {};

		/*!
		 *
		 * @brief Default destructor
		 *
		 */
		virtual ~CfgParserException() throw() {};

		/*!
		 *
		 * @brief Return the exception message.
		 *
		 */
		virtual const char* what() const throw();
	};


	/*!
	 *
	 * @brief DataExeption class.
	 * Responsible to throw exception for while using the Data class
	 *
	 */
	class DataException : public std::exception {

	protected :
		std::string error;

	public :

		/*!
		 *
		 * @brief Thrown constructor
		 *
		 */
		DataException(std::string const& er) throw() : error(er)  {};

		/*!
		 *
		 * @brief Default destructor
		 *
		 */
		virtual ~DataException() throw() {};

		/*!
		 *
		 * @brief Return the exception message.
		 *
		 */
		virtual const char* what() const throw();
	};



}  //  end namespace cfgparser

#endif  // CFGPARSEREXCEPTION_HH
