  /// \file SafeCfgParser.hh
/*
 *
 * SafeCfgParser.hh header template generated by fclass
 * Creation date : jeu. juin 6 2013
 *
 * This file is part of CfgParser libraries.
 *
 * CfgParser is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * CfgParser is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with CfgParser.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @author : Eté Rémi
 * @version 0.1.0 13/08/2013
 * @copyright 2013 Eté Rémi
 * 
 */


#ifndef SAFECFGPARSER_HH
#define SAFECFGPARSER_HH

#include "CfgParser.hh"

#include <iostream> 
#include <string> 
#include <cstdlib> 
#include <cmath> 
#include <vector> 

namespace cfgparser {

/* 
 * Class SafeCfgParser
 * Inherits from base class CfgParser
 */ 

class SafeCfgParser : public CfgParser {

  public:
    /*! Default Constructor */
    SafeCfgParser();
    /*! Default Destructor */
    virtual ~SafeCfgParser();

  protected:


};  // class 

}  // namespace 

#endif  //  SAFECFGPARSER_HH
