  /// \file SafeCfgParser.hh
/*
 *
 * SafeCfgParser.hh header template generated by fclass
 * Creation date : jeu. juin 6 2013
 * Copyright (c) CNRS , IPNL
 *
 * All Right Reserved.
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * @author : rete
 */


#ifndef SAFECFGPARSER_HH
#define SAFECFGPARSER_HH

#include "CfgParser.hh"

#include <iostream> 
#include <string> 
#include <cstdlib> 
#include <cmath> 
#include <vector> 

namespace cfgparser {

/* 
 * Class SafeCfgParser
 * Inherits from base class CfgParser
 */ 

class SafeCfgParser : public CfgParser {

  public:
    /*! Default Constructor */
    SafeCfgParser();
    /*! Default Destructor */
    virtual ~SafeCfgParser();

  protected:


};  // class 

}  // namespace 

#endif  //  SAFECFGPARSER_HH
