  /// \file Section.hh
/*
 *
 * Section.hh header template generated by fclass
 * Creation date : mar. juin 4 2013
 *
 * This file is part of CfgParser libraries.
 *
 * CfgParser is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * CfgParser is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with CfgParser.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @author : Eté Rémi
 * @version 0.1.0 13/08/2013
 * @copyright 2013 Eté Rémi
 * 
 */


#ifndef SECTION_HH
#define SECTION_HH

#include <iostream> 
#include <string> 
#include <cstdlib> 
#include <cmath> 
#include <vector>
#include <map>
#include <algorithm>
#include <sstream>

#include "ParserStatus.hh"
#include "StrOp.hh"

namespace cfgparser {


	class Section;
	class RawCfgParser;
	class CfgParser;
	class SafeCfgParser;

	typedef std::map <std::string,std::string> OptionValueMap;
	typedef std::vector<Section*> SectionCollection;
	typedef std::vector<const Section *> ConstSectionCollection;


	/*
	 * Class Section
	 */

	class Section {

		public:

			/*!
			 *
			 * Constructor with section name
			 *
			 */
			Section( const std::string &n );

			/*!
			 *
			 * Default Destructor
			 *
			 */
			virtual ~Section();

			/*!
			 *
			 * @brief Copy constructor
			 *
			 */
			Section( const Section &section );


		// protected members
		protected :

			std::string name;
			OptionValueMap optionValueMap;


		// public member functions
		public:

			/*!
			 *
			 * @brief Return the section name
			 *
			 */
			inline const std::string GetName() const
				{ return name; }

			/*!
			 *
			 * @brief Return a string value
			 *
			 */
			StatusCode GetValue( const std::string &k , std::string *value ) const;

			/*!
			 *
			 * @brief Return an int value
			 *
			 */
			StatusCode GetValue( const std::string &k , int *value ) const;

			/*!
			 *
			 * @brief Return a double value
			 *
			 */
			StatusCode GetValue( const std::string &k , double *value ) const;

			/*!
			 *
			 * @brief Return a bool value
			 *
			 */
			StatusCode GetValue( const std::string &k , bool *value ) const;

			/*!
			 *
			 * @brief Return a string vector value
			 *
			 */
			StatusCode GetValue( const std::string &k , std::vector<std::string> *value ) const;

			/*!
			 *
			 * @brief Return a double vector value
			 *
			 */
			StatusCode GetValue( const std::string &k , std::vector<double> *value ) const;

			/*!
			 *
			 * @brief Return an int vector value
			 *
			 */
			StatusCode GetValue( const std::string &option , std::vector<int> *value ) const;

			/*!
			 *
			 * @brief Return a bool vector value
			 *
			 */
			StatusCode GetValue( const std::string &option , std::vector<bool> *value ) const;

			/*!
			 *
			 * @brief Return true if the section contains the given option
			 *
			 */
			bool HasOption( const std::string &opt ) const;

			/*!
			 *
			 * @brief Return true if the section is empty
			 *
			 */
			bool IsEmpty() const;

			/*!
			 *
			 * @brief Return the Option/Value map containing all option-value pairs.
			 *
			 */
			inline const OptionValueMap GetOptionValueMap() const
				{ return optionValueMap; }

			/*!
			 *
			 * @brief Print the section with all option-value pairs
			 *
			 */
			StatusCode Print() const;


		protected:

			/*!
			 *
			 * @brief Clear the section
			 *
			 */
			StatusCode Clear();

			/*!
			 *
			 * @brief operator to add section
			 *
			 */
			Section& operator +=( const Section& section );

			/*!
			 *
			 * @brief Delete a a option from the section
			 *
			 */
			StatusCode RemoveOption( const std::string &opt );

			/*!
			 *
			 * @brief Append a option-value pair
			 *
			 */
			StatusCode SetValue( const std::string &option , const std::string &value );

			StatusCode SetValue( const std::string &option, const int &value );

			StatusCode SetValue( const std::string &option, const double &value );

			StatusCode SetValue( const std::string &option, const bool &value );

			StatusCode SetValue( const std::string &option, const std::vector< std::string > &value );

			StatusCode SetValue( const std::string &option, const std::vector< int > &value );

			StatusCode SetValue( const std::string &option, const std::vector< double > &value );

			StatusCode SetValue( const std::string &option, const std::vector< bool > &value );

			/*!
			 *
			 * @brief Set the section name
			 *
			 */
			inline void SetName( const std::string &n )
				{ name = n;}

			friend class RawCfgParser;
			friend class CfgParser;
			friend class SafeCfgParser;
			friend Section operator +( Section const& section1, Section const& section2 );

	};  // class

	/*!
	 *
	 * @brief operator to add section. Keep the name of the first section
	 *
	 */
	Section operator+ ( Section const& section1, Section const& section2 );

}  // namespace 

#endif  //  SECTION_HH
