/*
 *
 * StrOp.hh header template generated by fclass
 * Creation date : Mon Apr 15 15:17:05 2013
 *
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 *
 * Written by : rete
 */


#ifndef STROP_HH
#define STROP_HH

#include <iostream>
#include <fstream>
#include <string>
#include <list>
#include <cstdlib>
#include <sstream>
#include <map>
#include <vector>



namespace cfgparser {


	/*!
	 *
	 * @brief Normalize the name
	 *
	 */
	void NormalizeName( std::string *str );


	/*!
	 *
	 * @brief Trim spaces from the string 'str'
	 *
	 */
	void StrTrim( std::string *str );


}  //  end namespace cfgparser

#endif  // STROP_HH
