  /// \file ParserStatus.cc
/*
 *
 * ParserStatus.cc source template generated by fclass
 * Creation date : mar. juin 4 2013
 *
 * This file is part of CfgParser libraries.
 *
 * CfgParser is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * CfgParser is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with CfgParser.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author : Eté Rémi
 * @version 0.1.0 13/08/2013
 * @copyright 2013 Eté Rémi
 *
 */


#include "ParserStatus.hh"

using namespace std;

namespace cfgparser {


	string StatusCode::toString() const {

		if( _parserStatus == fParserSuccess )    return "fParserSuccess";
		else if( _parserStatus == fParserNoSectionError ) return "fParserNoSectionError";
		else if( _parserStatus == fParserError ) return "fParserError";
		else if( _parserStatus == fParserDuplicateSectionError ) return "fParserDuplicateSectionError";
		else if( _parserStatus == fParserNoOptionError ) return "fParserNoOptionError";
		else if( _parserStatus == fParserInterpolationError ) return "fParserInterpolationError";
		else if( _parserStatus == fParserInterpolationDepthError ) return "fParserInterpolationDepthError";
		else if( _parserStatus == fParserInterpolationMissingOptionError ) return "fParserInterpolationMissingOptionError";
		else if( _parserStatus == fParserInterpolationSyntaxError ) return "fParserInterpolationSyntaxError";
		else if( _parserStatus == fParserMissingSectionNameError ) return "fParserMissingSectionNameError";
		else if( _parserStatus == fParserInvalidSectionKey ) return "fParserInvalidSectionKey";
		else if( _parserStatus == fParserValueError ) return "fParserValueError";
		else return "fParserParsingError";
	}


	StatusCode CFGPARSER_SUCCESS( const std::string &message ) {

		StatusCode statusCode;
		statusCode._parserStatus = fParserSuccess;
		statusCode._message = message;
		return statusCode;
	}

	StatusCode CFGPARSER_ERROR( const std::string &message ) {

		StatusCode statusCode;
		statusCode._parserStatus = fParserError;
		statusCode._message = message;
		return statusCode;
	}

	StatusCode CFGPARSER_INVALID_SECTION_KEY( const std::string &message ) {

		StatusCode statusCode;
		statusCode._parserStatus = fParserInvalidSectionKey;
		statusCode._message = message;
		return statusCode;
	}

	StatusCode CFGPARSER_NO_SECTION_ERROR( const std::string &message ) {

		StatusCode statusCode;
		statusCode._parserStatus = fParserNoSectionError;
		statusCode._message = message;
		return statusCode;
	}

	StatusCode CFGPARSER_VALUE_ERROR( const std::string &message ) {

		StatusCode statusCode;
		statusCode._parserStatus = fParserValueError;
		statusCode._message = message;
		return statusCode;
	}

	StatusCode CFGPARSER_DUPLICATE_SECTION_ERROR( const std::string &message ) {

		StatusCode statusCode;
		statusCode._parserStatus = fParserDuplicateSectionError;
		statusCode._message = message;
		return statusCode;
	}

	StatusCode CFGPARSER_NO_OPTION_ERROR( const std::string &message ) {

		StatusCode statusCode;
		statusCode._parserStatus = fParserNoSectionError;
		statusCode._message = message;
		return statusCode;
	}

	StatusCode CFGPARSER_INTERPOLATION_DEPTH_ERROR( const std::string &message ) {

		StatusCode statusCode;
		statusCode._parserStatus = fParserInterpolationDepthError;
		statusCode._message = message;
		return statusCode;
	}

	StatusCode CFGPARSER_INTERPOLATION_MISSING_OPTION_ERROR( const std::string &message ) {

		StatusCode statusCode;
		statusCode._parserStatus = fParserInterpolationMissingOptionError;
		statusCode._message = message;
		return statusCode;
	}

	StatusCode CFGPARSER_INTERPOLATION_SYNTAX_ERROR( const std::string &message ) {

		StatusCode statusCode;
		statusCode._parserStatus = fParserInterpolationSyntaxError;
		statusCode._message = message;
		return statusCode;
	}

	StatusCode CFGPARSER_MISSING_SECTION_NAME_ERROR( const std::string &message ) {

		StatusCode statusCode;
		statusCode._parserStatus = fParserMissingSectionNameError;
		statusCode._message = message;
		return statusCode;
	}

	StatusCode CFGPARSER_PARSING_ERROR( const std::string &message ) {

		StatusCode statusCode;
		statusCode._parserStatus = fParserParsingError;
		statusCode._message = message;
		return statusCode;
	}

	StatusCode& StatusCode::operator = ( StatusCode const &statusCode ) {

		this->_message = statusCode._message;
		this->_parserStatus = statusCode._parserStatus;
		return *this;
	}


	bool operator != ( const StatusCode &sc1 , const StatusCode &sc2 ) {

		return ( sc1._parserStatus != sc2._parserStatus );
	}

	bool operator == ( const StatusCode &sc1 , const StatusCode &sc2 ) {

		return ( sc1._parserStatus == sc2._parserStatus );
	}



}  // namespace 

