  /// \file SafeCfgParser.cc
/*
 *
 * SafeCfgParser.cc source template generated by fclass
 * Creation date : jeu. juin 6 2013
 * Copyright (c) CNRS , IPNL
 *
 * All Right Reserved.
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * @author : rete
 */


#include "SafeCfgParser.hh"

using namespace std;

namespace cfgparser {

	SafeCfgParser::SafeCfgParser()
		: CfgParser() {

	}

	SafeCfgParser::~SafeCfgParser() {

	}


}  // namespace 

