/*
 *
 * StrOp.cc cpp file template generated by fclass
 * Creation date : Mon Apr 15 15:17:05 2013
 *
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 *
 * Written by : rete
 */


#include "StrOp.hh"



using namespace std ;


namespace cfgparser {


	void StrTrim( string *str ) {

		// count leading spaces
		int i = 0;

		while ( i < (int)str->length() && isspace((*str)[i]) ) ++i;

		// delete leading spaces
		if ( i > 0 ) str->erase(0, i);

		// last char position
		i = str->length();
		int j = i;
		while (i > 0 && isspace((*str)[i - 1])) --i;

		// delete trailing spaces
		if ( i < j ) str->erase( i, j );
	}


	void NormalizeName(string *str) {

		// trim spaces
		StrTrim(str);

		unsigned int i, j;
		i = 0;

		// shrink multi-spaces
		while ( i < str->length() ) {

			// if space
			if (isspace((*str)[i])) {

				// detect row of spaces
				j = i;
				while ( j + 1 < str->length() && isspace((*str)[j + 1]) )
					++j;

				// if more than one space in row
				if (i < j)
					str->erase(i, j);
				++i;
			}
			// lower case
			else (*str)[i] = tolower((*str)[i]);

			++i;
		}
	}



}  //  end namespace cfgparser

